name: Build Windows EXE

on:
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Create .env.production for Vite
        shell: bash
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env.production
          echo "VITE_SUPABASE_ANON=${{ secrets.VITE_SUPABASE_ANON }}" >> .env.production
          echo "VITE_SUPABASE_SCHEMA=public" >> .env.production

      - name: Build web (Vite)
        run: npm run build

      - name: Build Tauri (Windows)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ⬆️ args KALDIRILDI — default olarak `npm run tauri build` çalışır

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: src-tauri/target/release/bundle/nsis/*.exe
